// compat/apps/solid-vite/src/App.tsx
// Data layer "signals": Solid signals and createResource, idiomatic. The typeahead is a resource keyed by the query
// signal (Solid resolves only the latest fetch, so a cannot show stale results by construction); the create form
// has no in-flight guard (b). GenClass does not discover Solid signals (README: not covered yet).
import { For, Show, createResource, createSignal, onCleanup, onMount, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import * as api from "./api";

type NoteRow = { key: string; text: string; pending?: boolean };

function A() {
  const [q, setQ] = createSignal("");
  const [res] = createResource(q, (v) => api.search(v));
  const results = () => (q() ? (res.latest?.results ?? []) : []);
  return (
    <>
      <h2>City search</h2>
      <input data-testid="q" value={q()} onInput={(e) => setQ(e.currentTarget.value)} placeholder="Search cities" autocomplete="off" />
      <ul>
        <For each={results()}>{(r) => <li data-testid="result">{r}</li>}</For>
      </ul>
    </>
  );
}

function ItemList(p: { items: api.Item[] }) {
  return (
    <ul>
      <For each={p.items}>{(i) => <li data-testid="item">{i.title}</li>}</For>
    </ul>
  );
}

function CreateForm(p: { title: string; setTitle: (t: string) => void; onSubmit: () => void }) {
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        p.onSubmit();
      }}
    >
      <input data-testid="title" value={p.title} onInput={(e) => p.setTitle(e.currentTarget.value)} placeholder="New item" />
      <button data-testid="create" type="submit">
        Create
      </button>
    </form>
  );
}

function B() {
  const [items, { mutate }] = createResource(() => api.items().then((r) => r.items));
  const [title, setTitle] = createSignal("");
  const [error, setError] = createSignal<string | null>(null);
  const submit = async () => {
    try {
      const item = await api.createItem(title());
      mutate((xs) => [...(xs ?? []), item]);
      setTitle("");
    } catch {
      setError("Could not create");
    }
  };
  return (
    <>
      <h2>Items</h2>
      <CreateForm title={title()} setTitle={setTitle} onSubmit={submit} />
      <ItemList items={items.latest ?? []} />
      <Show when={error()}>
        <p data-testid="error">{error()}</p>
      </Show>
    </>
  );
}

function C() {
  const [go, setGo] = createSignal(false);
  const [left] = createResource(go, () => api.left());
  const [right] = createResource(go, () => api.right());
  return (
    <>
      <button data-testid="load" onClick={() => setGo(true)}>
        Load both
      </button>
      <section>
        <h3>People</h3>
        <ul>
          <For each={left.latest?.rows ?? []}>{(r) => <li data-testid="left-row">{r}</li>}</For>
        </ul>
      </section>
      <section>
        <h3>Activity</h3>
        <ul>
          <For each={right.latest?.rows ?? []}>{(r) => <li data-testid="right-row">{r}</li>}</For>
        </ul>
      </section>
    </>
  );
}

function D() {
  const [todos, { mutate }] = createResource(() => api.todos().then((r) => r.todos));
  const [error, setError] = createSignal<string | null>(null);
  const patch = (id: number, fn: (x: api.Todo) => api.Todo) => mutate((ts) => ts!.map((x) => (x.id === id ? fn(x) : x)));
  const toggle = async (t: api.Todo) => {
    const done = !t.done;
    patch(t.id, (x) => ({ ...x, done })); // optimistic
    try {
      const saved = await api.toggleTodo(t.id, done);
      patch(t.id, () => saved);
    } catch {
      patch(t.id, (x) => ({ ...x, done: t.done })); // roll back
      setError(`Could not save "${t.title}"`);
    }
  };
  return (
    <>
      <h2>Todos</h2>
      <ul>
        <For each={todos.latest ?? []}>
          {(t) => (
            <li data-testid="todo">
              <label>
                <input type="checkbox" data-testid={`toggle-${t.id}`} checked={t.done} onChange={() => void toggle(t)} />
                {t.title}: {t.done ? "done" : "open"}
              </label>
            </li>
          )}
        </For>
      </ul>
      <Show when={error()}>
        <p data-testid="error">{error()}</p>
      </Show>
    </>
  );
}

let noteSeq = 0;
function E() {
  const [notes, setNotes] = createSignal<NoteRow[] | null>(null);
  const [draft, setDraft] = createSignal("");
  onMount(() => void api.notes().then((r) => setNotes(r.notes.map((n) => ({ key: `s${n.id}`, text: n.text })))));
  const outbox = api.createOutbox<NoteRow>(async (row) => {
    try {
      const saved = await api.addNote(row.text);
      setNotes((ns) => ns!.map((n) => (n.key === row.key ? { key: `s${saved.id}`, text: saved.text } : n)));
      return true;
    } catch {
      return false;
    }
  });
  onCleanup(() => outbox.dispose());
  const add = () => {
    const row = { key: `l${++noteSeq}`, text: draft(), pending: true };
    setDraft("");
    setNotes((ns) => [...(ns ?? []), row]);
    void outbox.submit(row);
  };
  return (
    <>
      <h2>Notes</h2>
      <input data-testid="note-text" value={draft()} onInput={(e) => setDraft(e.currentTarget.value)} placeholder="Note" />
      <button data-testid="note-add" onClick={add}>
        Add
      </button>
      <ul>
        <For each={notes() ?? []}>
          {(n) => (
            <li data-testid="note">
              {n.text}
              {n.pending ? " (pending)" : ""}
            </li>
          )}
        </For>
      </ul>
    </>
  );
}

function F() {
  const [count, setCount] = createSignal(0);
  const [synced, setSynced] = createSignal(0);
  const plus = () => {
    setCount((c) => c + 1);
    api.increment().then((r) => setSynced((s) => Math.max(s, r.count)));
  };
  return (
    <>
      <button data-testid="plus" onClick={plus}>
        +1
      </button>
      <p>
        Count <span data-testid="count">{count()}</span>, saved <span data-testid="synced">{synced()}</span>
      </p>
    </>
  );
}

function LivePanel() {
  const [tick, setTick] = createSignal(0);
  const [polls, setPolls] = createSignal(0);
  const [details, setDetails] = createSignal<Record<number, api.Detail>>({});
  onMount(() => {
    for (const id of api.DETAIL_IDS) api.detail(id).then((d) => setDetails((m) => ({ ...m, [id]: d })));
    let stopped = false;
    let timer: ReturnType<typeof setTimeout>;
    const poll = async () => {
      const r = await api.status();
      if (stopped) return;
      setTick(r.tick);
      setPolls((p) => p + 1);
      if (r.tick < 8) timer = setTimeout(poll, 250);
    };
    void poll();
    onCleanup(() => {
      stopped = true;
      clearTimeout(timer);
    });
  });
  return (
    <div>
      <p>
        Tick <span data-testid="tick">{tick()}</span> after <span data-testid="polls">{polls()}</span> polls
      </p>
      <ul>
        <For each={api.DETAIL_IDS}>
          {(id) => (
            <Show when={details()[id]} fallback={<li>loading</li>}>
              {(d) => (
                <li data-testid="detail">
                  {d().name}: {d().price}
                </li>
              )}
            </Show>
          )}
        </For>
      </ul>
    </div>
  );
}

function G() {
  const [on, setOn] = createSignal(false);
  return (
    <>
      <button data-testid="start" onClick={() => setOn(true)}>
        Start
      </button>
      <Show when={on()}>
        <LivePanel />
      </Show>
    </>
  );
}

function H() {
  const [items, { mutate }] = createResource(() => api.items().then((r) => r.items));
  const [q, setQ] = createSignal("");
  const [res] = createResource(q, (v) => api.search(v));
  const [title, setTitle] = createSignal("");
  const create = async () => {
    const item = await api.createItem(title());
    mutate((xs) => [...(xs ?? []), item]);
    setTitle("");
  };
  return (
    <>
      <h2>Items</h2>
      <ItemList items={items.latest ?? []} />
      <CreateForm title={title()} setTitle={setTitle} onSubmit={() => void create()} />
      <h2>Search</h2>
      <input data-testid="q" value={q()} onInput={(e) => setQ(e.currentTarget.value)} placeholder="Search cities" autocomplete="off" />
      <ul>
        <For each={q() ? (res.latest?.results ?? []) : []}>{(r) => <li data-testid="result">{r}</li>}</For>
      </ul>
    </>
  );
}

const S: Record<string, Component> = { a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H };

export default function App() {
  const s = new URLSearchParams(location.search).get("s") ?? "h";
  const [mounted, setMounted] = createSignal(false);
  onMount(() => setMounted(true));
  return (
    <div id="compat" data-ready={mounted() ? "1" : "0"}>
      <Dynamic component={S[s] ?? H} />
    </div>
  );
}

// compat/apps/angular/src/app/page.ts
// The compat page (?s=<scenario a-h>): standalone components, signals, HttpClient subscriptions, written the common
// way: the typeahead subscribes per keystroke and sets whatever answer arrives (a: no switchMap), the create form has
// no in-flight guard (b). The other scenarios are correct. Rendered on the server, hydrated in the browser; data
// loads in the browser only (afterNextRender). GenClass does not discover Angular signals (README: not covered
// yet); it sees the network (fetch or XHR, by HttpClient backend) and user input.
import { Component, Injectable, afterNextRender, inject, signal, type OnDestroy } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { firstValueFrom } from 'rxjs';

type Item = { id: number; title: string };
type Panel = { version: number; rows: string[] };
type Todo = { id: number; title: string; done: boolean };
type Note = { id: number; text: string };
type Detail = { id: number; name: string; price: number };
type NoteRow = { key: string; text: string; pending?: boolean };
const DETAIL_IDS = [1, 2, 3, 4, 5, 6];

@Injectable({ providedIn: 'root' })
export class Api {
  private http = inject(HttpClient);
  search = (q: string) => this.http.get<{ q: string; results: string[] }>('/api/search', { params: { q } });
  items = () => this.http.get<{ items: Item[] }>('/api/items');
  createItem = (title: string) => this.http.post<Item>('/api/items', { title });
  left = () => this.http.get<Panel>('/api/left');
  right = () => this.http.get<Panel>('/api/right');
  todos = () => this.http.get<{ todos: Todo[] }>('/api/todos');
  toggleTodo = (id: number, done: boolean) => this.http.patch<Todo>(`/api/todos/${id}`, { done });
  notes = () => this.http.get<{ notes: Note[] }>('/api/notes');
  addNote = (text: string) => this.http.post<Note>('/api/notes', { text });
  increment = () => this.http.post<{ count: number }>('/api/counter/increment', {});
  status = () => this.http.get<{ tick: number }>('/api/status');
  detail = (id: number) => this.http.get<Detail>(`/api/detail/${id}`);
}

/** Offline outbox: rows that could not be sent are kept in order and sent again when the browser is back online. */
function createOutbox<T>(send: (row: T) => Promise<boolean>) {
  const queue: T[] = [];
  let flushing = false;
  async function flush() {
    if (flushing) return;
    flushing = true;
    try {
      while (queue.length) {
        if (!(await send(queue[0]))) break;
        queue.shift();
      }
    } finally {
      flushing = false;
    }
  }
  const onOnline = () => void flush();
  window.addEventListener('online', onOnline);
  return {
    async submit(row: T) {
      if (queue.length || flushing) return void queue.push(row);
      if (!(await send(row))) queue.push(row);
    },
    dispose: () => window.removeEventListener('online', onOnline),
  };
}

@Component({
  selector: 'app-a',
  template: `<h2>City search</h2>
    <input data-testid="q" [value]="q()" (input)="onQ($any($event.target).value)" placeholder="Search cities" autocomplete="off" />
    <ul>
      @for (r of results(); track r) {
        <li data-testid="result">{{ r }}</li>
      }
    </ul>`,
})
class A {
  private api = inject(Api);
  q = signal('');
  results = signal<string[]>([]);
  onQ(v: string) {
    this.q.set(v);
    if (!v) return this.results.set([]);
    this.api.search(v).subscribe({ next: (r) => this.results.set(r.results), error: () => {} });
  }
}

@Component({
  selector: 'app-b',
  template: `<h2>Items</h2>
    <form (submit)="$event.preventDefault(); create()">
      <input data-testid="title" [value]="title()" (input)="title.set($any($event.target).value)" placeholder="New item" />
      <button data-testid="create" type="submit">Create</button>
    </form>
    <ul>
      @for (i of items() ?? []; track i.id) {
        <li data-testid="item">{{ i.title }}</li>
      }
    </ul>
    @if (error()) {
      <p data-testid="error">{{ error() }}</p>
    }`,
})
class B {
  private api = inject(Api);
  items = signal<Item[] | null>(null);
  title = signal('');
  error = signal<string | null>(null);
  constructor() {
    afterNextRender(() => this.api.items().subscribe((r) => this.items.set(r.items)));
  }
  create() {
    this.api.createItem(this.title()).subscribe({
      next: (item) => {
        this.items.update((xs) => [...(xs ?? []), item]);
        this.title.set('');
      },
      error: () => this.error.set('Could not create'),
    });
  }
}

@Component({
  selector: 'app-c',
  template: `<button data-testid="load" (click)="load()">Load both</button>
    <section>
      <h3>People</h3>
      <ul>
        @for (r of left() ?? []; track r) {
          <li data-testid="left-row">{{ r }}</li>
        }
      </ul>
    </section>
    <section>
      <h3>Activity</h3>
      <ul>
        @for (r of right() ?? []; track r) {
          <li data-testid="right-row">{{ r }}</li>
        }
      </ul>
    </section>`,
})
class C {
  private api = inject(Api);
  left = signal<string[] | null>(null);
  right = signal<string[] | null>(null);
  load() {
    this.api.left().subscribe((p) => this.left.set(p.rows));
    this.api.right().subscribe((p) => this.right.set(p.rows));
  }
}

@Component({
  selector: 'app-d',
  template: `<h2>Todos</h2>
    <ul>
      @for (t of todos() ?? []; track t.id) {
        <li data-testid="todo">
          <label>
            <input type="checkbox" [attr.data-testid]="'toggle-' + t.id" [checked]="t.done" (change)="toggle(t)" />
            {{ t.title }}: {{ t.done ? 'done' : 'open' }}
          </label>
        </li>
      }
    </ul>
    @if (error()) {
      <p data-testid="error">{{ error() }}</p>
    }`,
})
class D {
  private api = inject(Api);
  todos = signal<Todo[] | null>(null);
  error = signal<string | null>(null);
  constructor() {
    afterNextRender(() => this.api.todos().subscribe((r) => this.todos.set(r.todos)));
  }
  private patch(id: number, fn: (x: Todo) => Todo) {
    this.todos.update((ts) => ts!.map((x) => (x.id === id ? fn(x) : x)));
  }
  toggle(t: Todo) {
    const done = !t.done;
    this.patch(t.id, (x) => ({ ...x, done })); // optimistic
    this.api.toggleTodo(t.id, done).subscribe({
      next: (saved) => this.patch(t.id, () => saved),
      error: () => {
        this.patch(t.id, (x) => ({ ...x, done: t.done })); // roll back
        this.error.set(`Could not save "${t.title}"`);
      },
    });
  }
}

let noteSeq = 0;
@Component({
  selector: 'app-e',
  template: `<h2>Notes</h2>
    <input data-testid="note-text" [value]="draft()" (input)="draft.set($any($event.target).value)" placeholder="Note" />
    <button data-testid="note-add" (click)="add()">Add</button>
    <ul>
      @for (n of notes() ?? []; track n.key) {
        <li data-testid="note">{{ n.text }}{{ n.pending ? ' (pending)' : '' }}</li>
      }
    </ul>`,
})
class E implements OnDestroy {
  private api = inject(Api);
  notes = signal<NoteRow[] | null>(null);
  draft = signal('');
  private outbox: ReturnType<typeof createOutbox<NoteRow>> | null = null;
  constructor() {
    afterNextRender(() => {
      this.api.notes().subscribe((r) => this.notes.set(r.notes.map((n) => ({ key: `s${n.id}`, text: n.text }))));
      this.outbox = createOutbox<NoteRow>(async (row) => {
        try {
          const saved = await firstValueFrom(this.api.addNote(row.text));
          this.notes.update((ns) => ns!.map((n) => (n.key === row.key ? { key: `s${saved.id}`, text: saved.text } : n)));
          return true;
        } catch {
          return false;
        }
      });
    });
  }
  add() {
    const row = { key: `l${++noteSeq}`, text: this.draft(), pending: true };
    this.draft.set('');
    this.notes.update((ns) => [...(ns ?? []), row]);
    void this.outbox?.submit(row);
  }
  ngOnDestroy() {
    this.outbox?.dispose();
  }
}

@Component({
  selector: 'app-f',
  template: `<button data-testid="plus" (click)="plus()">+1</button>
    <p>Count <span data-testid="count">{{ count() }}</span>, saved <span data-testid="synced">{{ synced() }}</span></p>`,
})
class F {
  private api = inject(Api);
  count = signal(0);
  synced = signal(0);
  plus() {
    this.count.update((c) => c + 1);
    this.api.increment().subscribe((r) => this.synced.update((s) => Math.max(s, r.count)));
  }
}

@Component({
  selector: 'app-live',
  template: `<div>
    <p>Tick <span data-testid="tick">{{ tick() }}</span> after <span data-testid="polls">{{ polls() }}</span> polls</p>
    <ul>
      @for (id of ids; track id) {
        @if (details()[id]; as d) {
          <li data-testid="detail">{{ d.name }}: {{ d.price }}</li>
        } @else {
          <li>loading</li>
        }
      }
    </ul>
  </div>`,
})
class LivePanel implements OnDestroy {
  private api = inject(Api);
  ids = DETAIL_IDS;
  tick = signal(0);
  polls = signal(0);
  details = signal<Record<number, Detail>>({});
  private stopped = false;
  private timer: ReturnType<typeof setTimeout> | undefined;
  constructor() {
    afterNextRender(() => {
      for (const id of DETAIL_IDS) this.api.detail(id).subscribe((d) => this.details.update((m) => ({ ...m, [id]: d })));
      this.poll();
    });
  }
  private poll() {
    this.api.status().subscribe((r) => {
      if (this.stopped) return;
      this.tick.set(r.tick);
      this.polls.update((p) => p + 1);
      if (r.tick < 8) this.timer = setTimeout(() => this.poll(), 250);
    });
  }
  ngOnDestroy() {
    this.stopped = true;
    clearTimeout(this.timer);
  }
}

@Component({
  selector: 'app-g',
  imports: [LivePanel],
  template: `<button data-testid="start" (click)="on.set(true)">Start</button>
    @if (on()) {
      <app-live />
    }`,
})
class G {
  on = signal(false);
}

@Component({
  selector: 'app-h',
  template: `<h2>Items</h2>
    <ul>
      @for (i of items() ?? []; track i.id) {
        <li data-testid="item">{{ i.title }}</li>
      }
    </ul>
    <form (submit)="$event.preventDefault(); create()">
      <input data-testid="title" [value]="title()" (input)="title.set($any($event.target).value)" placeholder="New item" />
      <button data-testid="create" type="submit">Create</button>
    </form>
    <h2>Search</h2>
    <input data-testid="q" [value]="q()" (input)="onQ($any($event.target).value)" placeholder="Search cities" autocomplete="off" />
    <ul>
      @for (r of results(); track r) {
        <li data-testid="result">{{ r }}</li>
      }
    </ul>`,
})
class H {
  private api = inject(Api);
  items = signal<Item[] | null>(null);
  title = signal('');
  q = signal('');
  results = signal<string[]>([]);
  constructor() {
    afterNextRender(() => this.api.items().subscribe((r) => this.items.set(r.items)));
  }
  onQ(v: string) {
    this.q.set(v);
    if (!v) return this.results.set([]);
    this.api.search(v).subscribe({ next: (r) => this.results.set(r.results), error: () => {} });
  }
  create() {
    this.api.createItem(this.title()).subscribe((item) => {
      this.items.update((xs) => [...(xs ?? []), item]);
      this.title.set('');
    });
  }
}

@Component({
  selector: 'app-page',
  imports: [A, B, C, D, E, F, G, H],
  template: `<div id="compat" data-ssr="1" [attr.data-ready]="ready() ? '1' : '0'">
    @switch (s) {
      @case ('a') { <app-a /> }
      @case ('b') { <app-b /> }
      @case ('c') { <app-c /> }
      @case ('d') { <app-d /> }
      @case ('e') { <app-e /> }
      @case ('f') { <app-f /> }
      @case ('g') { <app-g /> }
      @default { <app-h /> }
    }
  </div>`,
})
export class Page {
  s = inject(ActivatedRoute).snapshot.queryParamMap.get('s') ?? 'h';
  ready = signal(false);
  constructor() {
    afterNextRender(() => this.ready.set(true));
  }
}
